# Generated by Django 2.1.2 on 2018-10-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='unique_id',
            field=models.CharField(max_length=100),
        ),
    ]
