# Generated by Django 2.1.3 on 2018-11-13 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20181010_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egrul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('inn', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('ogrn', models.CharField(max_length=30, null=True)),
                ('resp_body', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
