# Generated by Django 2.1.3 on 2018-12-12 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('can_run', 'Can run task'),)},
        ),
    ]
