# Generated by Django 2.1.3 on 2018-12-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_avito_avitoresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitoresult',
            name='price',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='avitoresult',
            name='status',
            field=models.CharField(choices=[(0, 'In Queue'), (1, 'In work')], max_length=1),
        ),
    ]
