# Generated by Django 2.1.3 on 2018-12-28 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20181227_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avitoresult',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('NEW_RESULT', 'New Result'), ('NEW_ERROR', 'New With Error'), ('NEW_NOT_OK', 'New Not OK'), ('NEW_CANCELLED', 'New Cancelled'), ('CHECK', 'In check'), ('CHECK_ERROR', 'Check Error'), ('CHECK_CLOSED', 'Check Closed')], max_length=16),
        ),
    ]
