# Generated by Django 2.1.3 on 2018-12-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20181228_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoresult',
            name='repeat_every',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='avitoresult',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avitoresult',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('NEW_RESULT', 'New Result'), ('NEW_ERROR', 'New With Error'), ('NEW_NOT_OK', 'New Not OK'), ('NEW_CANCELLED', 'New Cancelled'), ('CHECK', 'In check'), ('CHECK_ERROR', 'Check Error'), ('CHECK_NOT_OK', 'Check Not OK')], max_length=16),
        ),
    ]
